### ISSUE TITLE
SerialChart.exe fails to start

### ISSUE THREAD

**Issue by schweers** [starlino/serialchart#11]
In the first instance this is for reference, as I feel that other users might stumble across the same issue.

I downloaded the read-to-use version as advised. But when I run SerialChart.exe an error occurs:
_This application failed to start because it could not find or load the Qt platform plugin "windows".
Available platform plugins are: windows
Reinstalling the application may fix this problem._

To fix this issue, I had to install [qt-opensource-windows-x86-mingw48_opengl-5.2.1.exe](https://download.qt.io/archive/qt/5.2/5.2.1/) and extend the Windows environment:
set QT_QPA_PLATFORM_PLUGIN_PATH=C:\Qt\Qt5.2.1\5.2.1\mingw48_32\plugins\platforms\ (http://stackoverflow.com/questions/20495620/qt-5-1-1-application-failed-to-start-because-platform-plugin-windows-is-missi#comment50075432_24192521)

**Comment by starlino** [comment]
This was fixed in version 0.3.4. So the above steeps should not be necessary. Thanks for work around !
